### ISSUE TITLE
pom引入不了

### ISSUE THREAD

**Issue by yuanyonglin** [dsc-cmt/spring-strategy-extend#4]
如题

**Comment by shengchaojie** [comment]
这个项目刚贡献到 cmt这个组织下 ，还没上传到公库

<dependency>
    <groupId>io.github.shengchaojie</groupId>
    <artifactId>spring-strategy-tool</artifactId>
    <version>1.2.0</version>
</dependency>

这个已经发布到maven公库

或者你自己本地install下也可以

**Comment by shengchaojie** [comment]
<dependency>
    <groupId>io.github.shengchaojie</groupId>
    <artifactId>spring-strategy-tool</artifactId>
    <version>1.2.0</version>
</dependency>

**Comment by yuanyonglin** [comment]
多谢
